### ISSUE TITLE
编译时 SIMPLE: Error configuring

### ISSUE THREAD

**Issue by Txxyyy** [licheedev/Android-SerialPort-API#10]

**Comment by Txxyyy** [comment]
![image](https://user-images.githubusercontent.com/20162834/57906649-4c857200-78ad-11e9-8b94-6a28e16c9a57.png)

**Comment by lewiswon** [comment]
是缺少ninja这个工具造成的，参考 [简书链接](https://www.jianshu.com/p/7265b775a350)

**Comment by licheedev** [comment]
参考 #13
