### ISSUE TITLE
jitpack上无法下载1.0.1的包，jitpack上显示的状态是error

### ISSUE THREAD

**Issue by scaupdc** [licheedev/Android-SerialPort-API#13]

**Comment by licheedev** [comment]
jitpack上面构建的代码版本是2017年的，他们服务器的编译环境应该更新了，那边拉的代码的gradle build tools插件比较老，不兼容了。
刚刚重新release了1.0.1，已经可以了。

**Comment by headbig947** [comment]
现在这个问题又复现了

**Comment by headbig947** [comment]
这个问题又复现了，应该怎么处理呢？ 
FAILURE: Build failed with an exception.
           
           * Where:
           Script 'D:\flutter\flutter_2.5.3\packages\flutter_tools\gradle\module_plugin_loader.gradle' line: 40
           
           * What went wrong:
           A problem occurred configuring root project 'android_generated'.
           > A problem occurred configuring project ':flutter'.
              > Could not resolve all dependencies for configuration ':flutter:embed'.
                 > Could not find com.github.licheedev.Android-SerialPort-API:serialport:1.0.1.
                   Searched in the following locations:
                     - https://dl.google.com/dl/android/maven2/com/github/licheedev/Android-SerialPort-API/serialport/1.0.1/serialport-1.0.1.pom
                     - https://repo.maven.apache.org/maven2/com/github/licheedev/Android-SerialPort-API/serialport/1.0.1/serialport-1.0.1.pom
                     -
https://storage.googleapis.com/download.flutter.io/com/github/licheedev/Android-SerialPort-API/serialport/1.0.1/serialport-1.0.1.pom
                     - https://jitpack.io/com/github/licheedev/Android-SerialPort-API/serialport/1.0.1/serialport-1.0.1.pom
                     - file:/D:/project/module/ym_scan_aar/sdk/libs/serialport-1.0.1.jar
                     - file:/D:/project/module/ym_scan_aar/sdk/libs/serialport.jar
                     -
https://mirrors.tuna.tsinghua.edu.cn/flutter/download.flutter.io/com/github/licheedev/Android-SerialPort-API/serialport/1.0.1/serialport-1.0.1.pom
                   Required by:
                       project :flutter
