### ISSUE TITLE
请问一下,同时读取多个串口,该如何操作

### ISSUE THREAD

**Issue by onebee** [licheedev/Android-SerialPort-API#17]
请问一下,同时读取多个串口,该如何操作

**Comment by tydqcjj** [comment]
多个串口就是多个InputStream，你想怎么读都行

**Comment by daochushilang** [comment]
请问一下同时打开两个串口，应该怎么区分数据，现在有数据混乱的现象，还有，如果我想要两个串口同时读取和接收数据，这部分代码应该怎么写呀？提问兄弟，你弄出来没？

**Comment by licheedev** [comment]
@daochushilang 
每个串口都开独立的读写线程。可以参考一下这个 
https://github.com/licheedev/SerialWorker

**Comment by daochushilang** [comment]
好的，谢谢，我看看，这部分，我找了好久，都不知道要怎么解决，好难呀



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "John Lee"<notifications@github.com&gt;; 
发送时间: 2019年11月30日(星期六) 上午10:24
收件人: "licheedev/Android-SerialPort-API"<Android-SerialPort-API@noreply.github.com&gt;; 
抄送: "到处是狼"<371718330@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [licheedev/Android-SerialPort-API] 请问一下,同时读取多个串口,该如何操作 (#17)




@daochushilang
 每个串口都开独立的读写线程。可以参考一下这个
 https://github.com/licheedev/SerialWorker

**Comment by master5277** [comment]
@daochushilang 
请问您最后解决两个串口同时读取和接收数据的问题了吗？如果解决了，可以分享一下您的代码或者开发思路吗？
