### ISSUE TITLE
请问下oppo和vivo的无法连接可能是啥原因？

### ISSUE THREAD

**Issue by FFcjs** [licheedev/Android-SerialPort-API#20]
我测试下来oppo和vivo的手机貌似在系统层有特殊处理导致我用串口线插上后无法获取到权限并打开，其他厂商的手机都不存在这个问题，请问有可能是啥原因？

**Comment by licheedev** [comment]
无知啊，一直都在专用的开发板上操作，没在手机上面用过串口。

**Comment by licheedev** [comment]
话说是什么串口线，能发个商品连接过来看看么？

**Comment by FFcjs** [comment]
type-c/micro-usb 转RJ45的线，京东上就有。这个问题解决了，需要在vivo和oppo上打开otg开关才能连接。
