### ISSUE TITLE
你好，大佬，遇到了一个棘手的问题，能否帮忙看下，万分感激   q：1014909632

### ISSUE THREAD

**Issue by FuXinLisc** [licheedev/Android-SerialPort-API#21]
关于设备连接电子秤，第一次总是返回电子秤传输过来的数据，之后才正常，请问这是什么原因呢？谢谢

**Comment by licheedev** [comment]
喵喵喵？

**Comment by FuXinLisc** [comment]
为什么用tcflush不能清空ttyUSB串口缓冲区的数据？&nbsp; 每次读取的时候，，总会先读取一段之前的缓存数据&nbsp; 感谢您的回复，万分感谢
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"John Lee"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年11月27日(星期三) 上午10:18
 收件人:&nbsp;"licheedev/Android-SerialPort-API"<Android-SerialPort-API@noreply.github.com&gt;;
 抄送:&nbsp;"kazike"<1014909632@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [licheedev/Android-SerialPort-API] 你好，大佬，遇到了一个棘手的问题，能否帮忙看下，万分感激 q：1014909632 (#21)

 

 
喵喵喵？

**Comment by FuXinLisc** [comment]
这个是我目前接收到的，很奇怪，每次我已经清除缓存了，还是不行&nbsp; 还是会读取之前的缓存

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"John Lee"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年11月27日(星期三) 上午10:18
 收件人:&nbsp;"licheedev/Android-SerialPort-API"<Android-SerialPort-API@noreply.github.com&gt;;
 抄送:&nbsp;"kazike"<1014909632@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [licheedev/Android-SerialPort-API] 你好，大佬，遇到了一个棘手的问题，能否帮忙看下，万分感激 q：1014909632 (#21)

 

 
喵喵喵？

**Comment by licheedev** [comment]
这就触及到我的知识盲区了.jpg

我主要还是写APP，对Linux和NDK没多少了解。如果是我的话，可能会选择记下开启串口的时间，读取数据后与这时间做比较，如果时间差<特定时间，直接舍弃掉这段数据。

**Comment by FuXinLisc** [comment]
是的，关键就是舍弃数据这块&nbsp; 有问题的&nbsp; 我试过了清除缓存数据也不行，删除文件也不行&nbsp; 实在是无解




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"John Lee"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月27日(星期三) 上午10:41
收件人:&nbsp;"licheedev/Android-SerialPort-API"<Android-SerialPort-API@noreply.github.com&gt;;
抄送:&nbsp;"kazike"<1014909632@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [licheedev/Android-SerialPort-API] 你好，大佬，遇到了一个棘手的问题，能否帮忙看下，万分感激   q：1014909632 (#21)




这就触及到我的知识盲区了.jpg
 
我主要还是写APP，对Linux和NDK没多少了解。如果是我的话，可能会选择记下开启串口的时间，读取数据后与这时间做比较，如果时间差<特定时间，直接舍弃掉这段数据。

**Comment by licheedev** [comment]
为啥有问题？问题是什么？
你的这个设备的工作情况是怎样的，是主动上报数据，还是请求应答？
这种基于流的通信，问题不外乎就粘包、少包、错包。舍弃掉数据，最多也就前面几个包少了，又不影响后面数据的接收。做好处理不影响正常后面的工作吧。

**Comment by FuXinLisc** [comment]
我下午试了一下  大致情况是这样的  就每次会先读取一段旧的数据，我想通过清除缓存的方式解决  发现没什么用好像

**Comment by licheedev** [comment]
我有点好奇你的代码是怎么写的。
一般的套路不是打开串口后，就专门开个读线程，然后while(true) {InputStream.read()}不停地读的么，这样除了一开始那一下，后面也不会读到旧的数据啊。

**Comment by FuXinLisc** [comment]
是的&nbsp;&nbsp;就是刚开始1-2秒时间 都是旧的数据&nbsp; 如果时间长点的话，旧数据会不会更多呢、？



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"John Lee"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月27日(星期三) 下午2:30
收件人:&nbsp;"licheedev/Android-SerialPort-API"<Android-SerialPort-API@noreply.github.com&gt;;
抄送:&nbsp;"kazike"<1014909632@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [licheedev/Android-SerialPort-API] 你好，大佬，遇到了一个棘手的问题，能否帮忙看下，万分感激   q：1014909632 (#21)




我有点好奇你的代码是怎么写的。
 一般的套路不是打开串口后，就专门开个读线程，然后while(true) {InputStream.read()}不停地读的么，这样除了一开始那一下，后面也不会读到旧的数据啊。

**Comment by FuXinLisc** [comment]
&nbsp;
  

 可否加个qq详细聊下&nbsp; 好截图&nbsp; 万分感谢

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"John Lee"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年11月27日(星期三) 下午2:30
 收件人:&nbsp;"licheedev/Android-SerialPort-API"<Android-SerialPort-API@noreply.github.com&gt;;
 抄送:&nbsp;"kazike"<1014909632@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [licheedev/Android-SerialPort-API] 你好，大佬，遇到了一个棘手的问题，能否帮忙看下，万分感激 q：1014909632 (#21)

 

 
我有点好奇你的代码是怎么写的。
一般的套路不是打开串口后，就专门开个读线程，然后while(true) {InputStream.read()}不停地读的么，这样除了一开始那一下，后面也不会读到旧的数据啊。
