### ISSUE TITLE
1位起始位怎么配置

### ISSUE THREAD

**Issue by terry111zc** [licheedev/Android-SerialPort-API#23]
你好，最新版本可以配置起始位吗？我现在 需要配置1位起始位，这个该怎么配置呢？

**Comment by licheedev** [comment]
貌似默认就固定1个起始位，在PC上用过几个串口调试工具，好像也没见过有配置起始位的。
> https://baike.baidu.com/item/%E8%B5%B7%E5%A7%8B%E4%BD%8D/22349383?fr=aladdin
> https://developer.android.com/things/sdk/pio/uart

**Comment by terry111zc** [comment]
哦，好的，谢谢。
