### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by avivsalman** [licheedev/Android-SerialPort-API#3]
hi, its don't work for me, maybe you can help me, 

can you give your email?

**Comment by TonyEasy** [comment]
me too

**Comment by licheedev** [comment]
@TonyEasy @avivsalman 
看是不是代理配置的问题，我手滑把代理加上去了。

https://github.com/licheedev/Android-SerialPort-API/commit/62d0067da7493f9be37d8033c0daca031aa33f4f
