### ISSUE TITLE
demo可以运行，但是不知道怎么使用调试，求文档

### ISSUE THREAD

**Issue by tyx627** [licheedev/Android-SerialPort-API#5]
如题，demo编译运行正常，但是不知道怎么测试，不会用，最近也要做串口通讯，求文档，求指导

**Comment by licheedev** [comment]
不知道你还需不需要，写了个小玩意
https://github.com/licheedev/Android-SerialPort-Tool

**Comment by tyx627** [comment]
谢谢，需要的，我先看看，有什么不明白的可能还要请教一下你哈
