### ISSUE TITLE
可否更新下，支持 Android 15 的 16KB 页面大小

### ISSUE THREAD

**Issue by kolyneh** [licheedev/Android-SerialPort-API#54]
如题，仅需在 CMakeLists.txt 最后添加：
```
target_link_options(
        serial_port
        PRIVATE
        "-Wl,-z,max-page-size=16384"
)
```
即可。

**Comment by licheedev** [comment]
我参考https://developer.android.google.cn/guide/practices/page-sizes?hl=zh-cn 页面捣鼓了下，编译出来个新版本`implementation 'com.licheedev:android-serialport:2.1.5'`，
分别用官方模拟器（API35 16K页面版）和Genymotion模拟器（Android11）测试了下，Genymotion模拟器收发正常，官方模拟器只能发数据，一旦收到数据，就会卡死闪退，所以我不确保打包出来的新版本没问题，测试条件有限，只能这样了。

**Comment by kolyneh** [comment]
谢谢！刚好我这儿只需要发数据，同样我也只能在模拟器上测试。
