### ISSUE TITLE
有分包的问题。

### ISSUE THREAD

**Issue by adminqqz** [licheedev/Android-SerialPort-API#6]
![tim 20180628104631](https://user-images.githubusercontent.com/12959954/42010289-8b77b306-7ac0-11e8-921e-857c71d00e79.png)

**Comment by licheedev** [comment]
正常现象，确定一下波特率对不对。
我这边波特率4800的，还有一次收到一个字节的情况。
基于流的，就不要期望一次能收到完整的且正确的，很多时候都需要结合协议解决粘包、分包的问题。
