### ISSUE TITLE
无法从https://jitpack.io下载库

### ISSUE THREAD

**Issue by wildfire810** [licheedev/Android-SerialPort-API#7]
一个之前正常的工程，重新编译的时候，发现不能下载库文件

https://jitpack.io/com/github/licheedev/Android-serialPort-API/serialport/1.0.1/serialport-1.0.1.pom
https://jitpack.io/com/github/licheedev/Android-serialPort-API/serialport/1.0.1/serialport-1.0.1.jar
这两个打开，都会显示
Build failed. See the log at jitpack.io
我打开https://jitpack.io/com/github/licheedev/Android-SerialPort-API/1.0.1/build.log
看了，是正常的。

Android Studio显示如下
Could not find com.github.licheedev.Android-serialPort-API:serialport:1.0.1.
Searched in the following locations:
    file:/D:/Android/Sdk/extras/m2repository/com/github/licheedev/Android-serialPort-API/serialport/1.0.1/serialport-1.0.1.pom
    file:/D:/Android/Sdk/extras/m2repository/com/github/licheedev/Android-serialPort-API/serialport/1.0.1/serialport-1.0.1.jar
    file:/D:/Android/Sdk/extras/google/m2repository/com/github/licheedev/Android-serialPort-API/serialport/1.0.1/serialport-1.0.1.pom
    file:/D:/Android/Sdk/extras/google/m2repository/com/github/licheedev/Android-serialPort-API/serialport/1.0.1/serialport-1.0.1.jar
    file:/D:/Android/Sdk/extras/android/m2repository/com/github/licheedev/Android-serialPort-API/serialport/1.0.1/serialport-1.0.1.pom
    file:/D:/Android/Sdk/extras/android/m2repository/com/github/licheedev/Android-serialPort-API/serialport/1.0.1/serialport-1.0.1.jar
    https://dl.google.com/dl/android/maven2/com/github/licheedev/Android-serialPort-API/serialport/1.0.1/serialport-1.0.1.pom
    https://dl.google.com/dl/android/maven2/com/github/licheedev/Android-serialPort-API/serialport/1.0.1/serialport-1.0.1.jar
    https://jcenter.bintray.com/com/github/licheedev/Android-serialPort-API/serialport/1.0.1/serialport-1.0.1.pom
    https://jcenter.bintray.com/com/github/licheedev/Android-serialPort-API/serialport/1.0.1/serialport-1.0.1.jar
    https://jitpack.io/com/github/licheedev/Android-serialPort-API/serialport/1.0.1/serialport-1.0.1.pom
    https://jitpack.io/com/github/licheedev/Android-serialPort-API/serialport/1.0.1/serialport-1.0.1.jar
    http://maven.aliyun.com/nexus/content/repositories/releases/com/github/licheedev/Android-serialPort-API/serialport/1.0.1/serialport-1.0.1.pom
    http://maven.aliyun.com/nexus/content/repositories/releases/com/github/licheedev/Android-serialPort-API/serialport/1.0.1/serialport-1.0.1.jar

**Comment by Nerkey** [comment]
怎么解决的呢???

**Comment by licheedev** [comment]
参考 #13
